# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/ecc.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_ECCCipher(object):
    def setupUi(self, ECCCipher):
        ECCCipher.setObjectName("ECCCipher")
        ECCCipher.resize(527, 399)
        ECCCipher.setStyleSheet("\n"
"QMainWindow {\n"
"    background-color: #f4f7fb;\n"
"}\n"
"\n"
"QWidget {\n"
"    font-family: \"Segoe UI\", \"Arial\";\n"
"    font-size: 10pt;\n"
"    color: #2c3e50;\n"
"}\n"
"\n"
"QFrame#mainFrame {\n"
"    background-color: white;\n"
"    border: 1px solid #dfe6ee;\n"
"    border-radius: 16px;\n"
"}\n"
"\n"
"QLabel#label_title {\n"
"    color: #1f2d3d;\n"
"    font-size: 18pt;\n"
"    font-weight: bold;\n"
"}\n"
"\n"
"QLabel#label_information,\n"
"QLabel#label_signature {\n"
"    font-size: 10.5pt;\n"
"    font-weight: 600;\n"
"    color: #34495e;\n"
"}\n"
"\n"
"QPlainTextEdit {\n"
"    background-color: #f9fbfd;\n"
"    border: 1px solid #cfd8e3;\n"
"    border-radius: 10px;\n"
"    padding: 8px;\n"
"    selection-background-color: #4a90e2;\n"
"}\n"
"\n"
"QPlainTextEdit:focus {\n"
"    border: 1px solid #4a90e2;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QPushButton {\n"
"    border: none;\n"
"    border-radius: 10px;\n"
"    padding: 8px 14px;\n"
"    font-weight: 600;\n"
"    color: white;\n"
"    background-color: #4a90e2;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #357abd;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #2d6399;\n"
"}\n"
"\n"
"QPushButton#btn_generate_keys {\n"
"    background-color: #27ae60;\n"
"}\n"
"\n"
"QPushButton#btn_generate_keys:hover {\n"
"    background-color: #219150;\n"
"}\n"
"\n"
"QPushButton#btn_generate_keys:pressed {\n"
"    background-color: #1b7a43;\n"
"}\n"
"\n"
"QPushButton#btn_verify {\n"
"    background-color: #8e44ad;\n"
"}\n"
"\n"
"QPushButton#btn_verify:hover {\n"
"    background-color: #7a3796;\n"
"}\n"
"\n"
"QPushButton#btn_verify:pressed {\n"
"    background-color: #652d7a;\n"
"}\n"
"   ")
        self.centralwidget = QtWidgets.QWidget(ECCCipher)
        self.centralwidget.setObjectName("centralwidget")
        self.mainFrame = QtWidgets.QFrame(self.centralwidget)
        self.mainFrame.setGeometry(QtCore.QRect(20, 20, 480, 351))
        self.mainFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.mainFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.mainFrame.setObjectName("mainFrame")
        self.label_title = QtWidgets.QLabel(self.mainFrame)
        self.label_title.setGeometry(QtCore.QRect(30, 20, 220, 32))
        self.label_title.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_title.setObjectName("label_title")
        self.btn_generate_keys = QtWidgets.QPushButton(self.mainFrame)
        self.btn_generate_keys.setGeometry(QtCore.QRect(320, 20, 151, 36))
        self.btn_generate_keys.setObjectName("btn_generate_keys")
        self.label_information = QtWidgets.QLabel(self.mainFrame)
        self.label_information.setGeometry(QtCore.QRect(30, 80, 100, 24))
        self.label_information.setObjectName("label_information")
        self.txt_information = QtWidgets.QPlainTextEdit(self.mainFrame)
        self.txt_information.setGeometry(QtCore.QRect(30, 110, 420, 70))
        self.txt_information.setObjectName("txt_information")
        self.label_signature = QtWidgets.QLabel(self.mainFrame)
        self.label_signature.setGeometry(QtCore.QRect(30, 190, 100, 24))
        self.label_signature.setObjectName("label_signature")
        self.txt_signature = QtWidgets.QPlainTextEdit(self.mainFrame)
        self.txt_signature.setGeometry(QtCore.QRect(30, 220, 420, 70))
        self.txt_signature.setObjectName("txt_signature")
        self.btn_sign = QtWidgets.QPushButton(self.mainFrame)
        self.btn_sign.setGeometry(QtCore.QRect(150, 300, 90, 36))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(self.mainFrame)
        self.btn_verify.setGeometry(QtCore.QRect(260, 300, 90, 36))
        self.btn_verify.setObjectName("btn_verify")
        ECCCipher.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(ECCCipher)
        self.statusbar.setObjectName("statusbar")
        ECCCipher.setStatusBar(self.statusbar)

        self.retranslateUi(ECCCipher)
        QtCore.QMetaObject.connectSlotsByName(ECCCipher)

    def retranslateUi(self, ECCCipher):
        _translate = QtCore.QCoreApplication.translate
        ECCCipher.setWindowTitle(_translate("ECCCipher", "ECC Cipher"))
        self.label_title.setText(_translate("ECCCipher", "ECC CIPHER"))
        self.btn_generate_keys.setText(_translate("ECCCipher", "Generate Keys"))
        self.label_information.setText(_translate("ECCCipher", "Information"))
        self.txt_information.setPlaceholderText(_translate("ECCCipher", "Enter information to sign..."))
        self.label_signature.setText(_translate("ECCCipher", "Signature"))
        self.txt_signature.setPlaceholderText(_translate("ECCCipher", "Signature result will appear here..."))
        self.btn_sign.setText(_translate("ECCCipher", "Sign"))
        self.btn_verify.setText(_translate("ECCCipher", "Verify"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    ECCCipher = QtWidgets.QMainWindow()
    ui = Ui_ECCCipher()
    ui.setupUi(ECCCipher)
    ECCCipher.show()
    sys.exit(app.exec_())
