# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file './ui/rsa.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
import os
os.environ['QT_QPA_PLATFORM_PLUGIN_PATH'] = "../platforms"

class Ui_RSA_Cipher(object):
    def setupUi(self, RSA_Cipher):
        RSA_Cipher.setObjectName("RSA_Cipher")
        RSA_Cipher.resize(900, 500)
        RSA_Cipher.setStyleSheet("QMainWindow {\n"
"    background-color: #0f172a;\n"
"}\n"
"\n"
"QWidget#centralwidget {\n"
"    background-color: #0f172a;\n"
"}\n"
"\n"
"QLabel {\n"
"    color: #e2e8f0;\n"
"    font: 10pt \"Segoe UI\";\n"
"}\n"
"\n"
"QLabel#label_title {\n"
"    color: #f8fafc;\n"
"    background-color: #1e293b;\n"
"    border: 2px solid #38bdf8;\n"
"    border-radius: 14px;\n"
"    padding: 10px;\n"
"    font: 700 20pt \"Segoe UI\";\n"
"}\n"
"\n"
"QPlainTextEdit {\n"
"    background-color: #f8fafc;\n"
"    color: #0f172a;\n"
"    border: 2px solid #cbd5e1;\n"
"    border-radius: 12px;\n"
"    padding: 8px;\n"
"    font: 10pt \"Consolas\";\n"
"    selection-background-color: #38bdf8;\n"
"}\n"
"\n"
"QPlainTextEdit:focus {\n"
"    border: 2px solid #38bdf8;\n"
"    background-color: #ffffff;\n"
"}\n"
"\n"
"QPushButton {\n"
"    background-color: #2563eb;\n"
"    color: white;\n"
"    border: none;\n"
"    border-radius: 12px;\n"
"    font: 700 10pt \"Segoe UI\";\n"
"    padding: 8px 14px;\n"
"}\n"
"\n"
"QPushButton:hover {\n"
"    background-color: #3b82f6;\n"
"}\n"
"\n"
"QPushButton:pressed {\n"
"    background-color: #1d4ed8;\n"
"}\n"
"\n"
"QPushButton#btn_generate_keys {\n"
"    background-color: #7c3aed;\n"
"}\n"
"\n"
"QPushButton#btn_generate_keys:hover {\n"
"    background-color: #8b5cf6;\n"
"}\n"
"\n"
"QPushButton#btn_sign {\n"
"    background-color: #059669;\n"
"}\n"
"\n"
"QPushButton#btn_sign:hover {\n"
"    background-color: #10b981;\n"
"}\n"
"\n"
"QPushButton#btn_verify {\n"
"    background-color: #ea580c;\n"
"}\n"
"\n"
"QPushButton#btn_verify:hover {\n"
"    background-color: #f97316;\n"
"}\n"
"\n"
"QStatusBar {\n"
"    background-color: #1e293b;\n"
"    color: #e2e8f0;\n"
"}")
        self.centralwidget = QtWidgets.QWidget(RSA_Cipher)
        self.centralwidget.setObjectName("centralwidget")
        self.frame_left = QtWidgets.QFrame(self.centralwidget)
        self.frame_left.setGeometry(QtCore.QRect(30, 80, 390, 371))
        self.frame_left.setStyleSheet("QFrame#frame_left {\n"
"    background-color: #1e293b;\n"
"    border: 1px solid #334155;\n"
"    border-radius: 18px;\n"
"}")
        self.frame_left.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_left.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_left.setObjectName("frame_left")
        self.label_plain_text = QtWidgets.QLabel(self.frame_left)
        self.label_plain_text.setGeometry(QtCore.QRect(25, 20, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_plain_text.setFont(font)
        self.label_plain_text.setObjectName("label_plain_text")
        self.txt_plain_text = QtWidgets.QPlainTextEdit(self.frame_left)
        self.txt_plain_text.setGeometry(QtCore.QRect(25, 55, 340, 100))
        self.txt_plain_text.setObjectName("txt_plain_text")
        self.label_cipher_text = QtWidgets.QLabel(self.frame_left)
        self.label_cipher_text.setGeometry(QtCore.QRect(25, 175, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_cipher_text.setFont(font)
        self.label_cipher_text.setObjectName("label_cipher_text")
        self.txt_cipher_text = QtWidgets.QPlainTextEdit(self.frame_left)
        self.txt_cipher_text.setGeometry(QtCore.QRect(25, 210, 340, 100))
        self.txt_cipher_text.setObjectName("txt_cipher_text")
        self.btn_encrypt = QtWidgets.QPushButton(self.frame_left)
        self.btn_encrypt.setGeometry(QtCore.QRect(60, 325, 110, 35))
        self.btn_encrypt.setObjectName("btn_encrypt")
        self.btn_decrypt = QtWidgets.QPushButton(self.frame_left)
        self.btn_decrypt.setGeometry(QtCore.QRect(215, 325, 110, 35))
        self.btn_decrypt.setObjectName("btn_decrypt")
        self.frame_right = QtWidgets.QFrame(self.centralwidget)
        self.frame_right.setGeometry(QtCore.QRect(470, 80, 390, 371))
        self.frame_right.setStyleSheet("QFrame#frame_right {\n"
"    background-color: #1e293b;\n"
"    border: 1px solid #334155;\n"
"    border-radius: 18px;\n"
"}")
        self.frame_right.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_right.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_right.setObjectName("frame_right")
        self.label_information = QtWidgets.QLabel(self.frame_right)
        self.label_information.setGeometry(QtCore.QRect(25, 20, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_information.setFont(font)
        self.label_information.setObjectName("label_information")
        self.txt_information = QtWidgets.QPlainTextEdit(self.frame_right)
        self.txt_information.setGeometry(QtCore.QRect(25, 55, 340, 100))
        self.txt_information.setObjectName("txt_information")
        self.label_signature = QtWidgets.QLabel(self.frame_right)
        self.label_signature.setGeometry(QtCore.QRect(25, 175, 120, 30))
        font = QtGui.QFont()
        font.setFamily("Segoe UI")
        font.setPointSize(10)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label_signature.setFont(font)
        self.label_signature.setObjectName("label_signature")
        self.txt_signature = QtWidgets.QPlainTextEdit(self.frame_right)
        self.txt_signature.setGeometry(QtCore.QRect(25, 210, 340, 100))
        self.txt_signature.setObjectName("txt_signature")
        self.btn_sign = QtWidgets.QPushButton(self.frame_right)
        self.btn_sign.setGeometry(QtCore.QRect(60, 325, 110, 35))
        self.btn_sign.setObjectName("btn_sign")
        self.btn_verify = QtWidgets.QPushButton(self.frame_right)
        self.btn_verify.setGeometry(QtCore.QRect(215, 325, 110, 35))
        self.btn_verify.setObjectName("btn_verify")
        self.label_title = QtWidgets.QLabel(self.centralwidget)
        self.label_title.setGeometry(QtCore.QRect(280, 20, 340, 51))
        self.label_title.setAlignment(QtCore.Qt.AlignCenter)
        self.label_title.setObjectName("label_title")
        self.btn_generate_keys = QtWidgets.QPushButton(self.centralwidget)
        self.btn_generate_keys.setGeometry(QtCore.QRect(700, 25, 161, 36))
        self.btn_generate_keys.setObjectName("btn_generate_keys")
        RSA_Cipher.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(RSA_Cipher)
        self.statusbar.setObjectName("statusbar")
        RSA_Cipher.setStatusBar(self.statusbar)

        self.retranslateUi(RSA_Cipher)
        QtCore.QMetaObject.connectSlotsByName(RSA_Cipher)

    def retranslateUi(self, RSA_Cipher):
        _translate = QtCore.QCoreApplication.translate
        RSA_Cipher.setWindowTitle(_translate("RSA_Cipher", "RSA Cipher"))
        self.label_plain_text.setText(_translate("RSA_Cipher", "Plain Text"))
        self.label_cipher_text.setText(_translate("RSA_Cipher", "Cipher Text"))
        self.btn_encrypt.setText(_translate("RSA_Cipher", "Encrypt"))
        self.btn_decrypt.setText(_translate("RSA_Cipher", "Decrypt"))
        self.label_information.setText(_translate("RSA_Cipher", "Information"))
        self.label_signature.setText(_translate("RSA_Cipher", "Signature"))
        self.btn_sign.setText(_translate("RSA_Cipher", "Sign"))
        self.btn_verify.setText(_translate("RSA_Cipher", "Verify"))
        self.label_title.setText(_translate("RSA_Cipher", "RSA CIPHER"))
        self.btn_generate_keys.setText(_translate("RSA_Cipher", "Generate Keys"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RSA_Cipher = QtWidgets.QMainWindow()
    ui = Ui_RSA_Cipher()
    ui.setupUi(RSA_Cipher)
    RSA_Cipher.show()
    sys.exit(app.exec_())
